const allBeats = [
  {
    id: 1,
    title: "BB Do Anália",
    genre: "Funk",
    bpm: 132,
    key: "A#m",
    price: 139.90,
    originalPrice: 159.90,
    image: "imgs/capas/bbdoanalia.jpg",
    preview: "audios/previa-bb-do-analia.mp3",
    description: "Beat de Funk estilo Mc Gp x Mc Meno K",
    vibe: ["MC Gp", "MC Menor K"],
    onPromotion: true,
    purchaseLink: "https://pay.kirvano.com/733190ac-9fe6-4d8e-ac12-a83670c45f3e"
  },
  {
    id: 2,
    title: "Ela é Modelo",
    genre: "Funk",
    bpm: 120,
    key: "C#m",
    price: 149.90,
    image: "imgs/capas/capaelaemodelo.jpg",
    preview: "audios/previa-ela-e-modelo.mp3",
    description: "Beat de funk estilo Menor Mc x Mc Don Juan",
    vibe: ["Menor Mc", "Mc Don Juan"],
    purchaseLink: "https://pay.kirvano.com/d800f78d-64aa-4bef-8b25-f46eb91869a7"
  },
  {
    id: 3,
    title: "Lipo Pad",
    genre: "Funk",
    bpm: 123,
    key: "Bm",
    price: 149.90,
    image: "imgs/capas/capalipolad.jpg",
    preview: "audios/lipopad-previa.mp3",
    description: "Beat de funk estilo Mc luuky x Mc Tuto",
    vibe: ["MC Luuky", "Mc Tuto"],
    purchaseLink: "https://pay.kirvano.com/9a7e1e38-7842-459f-8e91-7ffc7705a647"
  },
  {
    id: 4,
    title: "Lacoste",
    genre: "Funk",
    bpm: 120,
    key: "Fm",
    price: 149.90,
    image: "imgs/capas/capalacoste.jpg",
    preview: "audios/previa-lacoste.mp3",
    description: "Beat de funk estilo Mc Ig x Mc Lele Jp",
    vibe: ["MC Ig", "MC Lele Jp"],
    purchaseLink: "https://pay.kirvano.com/807e8e9a-994d-49d3-ae61-85256494b586"
  },
  {
    id: 5,
    title: "Maria",
    genre: "Trap",
    bpm: 138,
    key: "G#m",
    price: 139.90,
    originalPrice: 159.90,
    image: "imgs/capas/capamaria.jpg",
    preview: "audios/previa-maria.mp3",
    description: "Beat de trap estilo Caio Luccas x Felipe Ret",
    vibe: ["Felipe Ret", "Caio Luccas"],
    onPromotion: true,
    purchaseLink: "https://pay.kirvano.com/ef83bed7-9cbc-4bf7-9c9c-28d777ca5d60"
  },
  {
    id: 6,
    title: "SLAP",
    genre: "Trap",
    bpm: 140,
    key: "Fm",
    price: 149.90,
    image: "imgs/capas/capaslap.jpg",
    preview: "audios/previa-slap.mp3",
    description: "Beat de Trap estilo Leviano x Alee",
    vibe: ["Leviano", "Alee"],
    purchaseLink: "https://pay.kirvano.com/e75662f2-8b00-4297-aea2-1a6f0bb759b8"
  },
  {
    id: 7,
    title: "Folder",
    genre: "Trap",
    bpm: 126,
    key: "Gm",
    price: 149.90,
    image: "imgs/capas/capafolder.jpg",
    preview: "audios/previa-folder.mp3",
    description: "Beat de trap estilo Yunk Vino x Veigh",
    vibe: ["Veigh", "Yunk Vino"],
    purchaseLink: "https://pay.kirvano.com/c6832eda-fbc8-432b-b160-6ea2260060a3"
  },
  {
    id: 8,
    title: "Fragments",
    genre: "Hood Trap",
    bpm: 140,
    key: "Fm",
    price: 149.90,
    image: "imgs/capas/capafragments.jpg",
    preview: "audios/previa-fragments.mp3",
    description: "Beat de HoodTrap estilo Niink x Supernova",
    vibe: ["Niink", "Supernova"],
    purchaseLink: "https://pay.kirvano.com/c5160f92-da4c-4117-a7b7-258d038a2b1e"
  },
  {
    id: 9,
    title: "Hermosa",
    genre: "Trap",
    bpm: 147,
    key: "Dm",
    price: 139.90,
    originalPrice: 159.90,
    image: "imgs/capas/capahermosa.jpg",
    preview: "audios/previa-hermosa.mp3",
    description: "Beat de trap estilo Vulgo Fk x Kayblack",
    vibe: ["Vulgo Fk", "Kayblack"],
    onPromotion: true,
    purchaseLink: "https://pay.kirvano.com/bb8c86c5-4262-4349-b7be-1b9371b80d52"
  },
  {
    id: 10,
    title: "ILYA",
    genre: "Trap",
    bpm: 122,
    key: "Cm",
    price: 149.90,
    image: "imgs/capas/capailya.jpg",
    preview: "audios/previa-ilya.mp3",
    description: "Beat de trap estilo Tz da Coronel x Mc Cabelinho",
    vibe: ["Tz da Coronel", "Mc Cabelinho"],
    purchaseLink: "https://pay.kirvano.com/ec832f39-65af-40af-8a56-92003f318d1f"
  },
  {
    id: 11,
    title: "Yes Sir",
    genre: "Trap",
    bpm: 140,
    key: "G#m",
    price: 149.90,
    image: "imgs/capas/capayessir.jpg",
    preview: "audios/previa-yessir.mp3",
    description: "Beat de Trap estilo Teto x Wiu",
    vibe: ["Teto", "Wiu"],
    purchaseLink: "https://pay.kirvano.com/14c6c663-ee95-4634-a02c-53708b853bfd"
  },
  {
    id: 12,
    title: "No More New Jazz",
    genre: "New Jazz",
    bpm: 128,
    key: "Em",
    price: 149.90,
    image: "imgs/capas/capanomore.jpg",
    preview: "audios/previa-nomore.mp3",
    description: "Beat de New Jazz estilo Lil Tecca",
    vibe: ["Lil Tecca"],
    purchaseLink: "https://pay.kirvano.com/5740b606-c367-48d1-a748-d3015930f5d5"
  }
];